# @name get-professors
GET http://localhost:3333/professors

###

# @name create-professor

POST http://localhost:3333/professor/cadastrar
Content-Type: application/json

{
  "name": "João Victor Teste 3",
  "phoneNumber": "123456789",
  "email": "joaov123@gmail.com",
  "address": "rua 1234"
}

###

# @name delete-professor

DELETE http://localhost:3333/professor/deletar
Content-Type: application/json

{
  "email": "teste123_victor@gmail.com"
}

###

# @name update-professor

PUT http://localhost:3333/professor/editar/joao321@gmail.com
Content-Type: application/json

{
  "name": "Novo Nome 123",
  "phoneNumber": "987654321",
  "address": "Nova Rua 123"
}

###

# @name find-professor-dy-email

GET http://localhost:3333/professor/joaov123@gmail.com
Content-Type: application/json
